image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://docker:2375"
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - staging
  - production

npm-build:
    stage: build
    image: trion/ng-cli
    script:
      - npm install
      - ng build


docker-build_image_develop:
  stage: package
  script:
  - docker build -t comparit/compare-it-front:develop .
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  - docker push comparit/compare-it-front:develop
  only:
  - develop

docker-build_image_master:
  stage: package
  script:
    - docker build -t comparit/compare-it-front:master .
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker push comparit/compare-it-front:master
  only:
    - master

job_deploy_staging:
  image: rastasheep/ubuntu-sshd
  stage: staging
  script:
  - echo "deploy the app into test (valserver)"
  - pwd
  - ls
  - chmod 600 ../compare-it-front.tmp/SSH_PEM_KEY
  - ssh -i $SSH_PEM_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@compit.ddns.net './start_project'
  environment:
    name: staging
  only:
  - develop

job_deploy_prod:
  image: rastasheep/ubuntu-sshd
  stage: production
  script:
  - echo "deploy the app into prod"
  - pwd
  - ls
  - chmod 600 ../compare-it-front.tmp/SSH_PEM_KEY
  - ssh -i $SSH_PEM_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null msn@compit2.northeurope.cloudapp.azure.com './start_project'
  environment:
    name: production
  only:
  - master


